<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources\OrderResource\RelationManagers;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\CreateAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;

class OrderLog extends RelationManager
{
    protected static string $relationship = 'orderLogs';

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.order_logs.single');
    }

    public static function getModelLabel(): ?string
    {
        return trans('filament-ecommerce::messages.order_logs.single');
    }

    public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return trans('filament-ecommerce::messages.order_logs.title');
    }

    protected static function getPluralModelLabel(): ?string
    {
        return trans('filament-ecommerce::messages.order_logs.title');
    }

    public function form(Schema $schema): Schema
    {
        return $schema->components([
            TextInput::make('user_id')
                ->hidden()
                ->default(auth()->user()->id)
                ->label(trans('filament-ecommerce::messages.order_logs.columns.user_id'))
                ->numeric(),
            TextInput::make('status')
                ->default($this->getOwnerRecord()->status)
                ->hidden()
                ->label(trans('filament-ecommerce::messages.order_logs.columns.status'))
                ->maxLength(255),
            Textarea::make('note')
                ->label(trans('filament-ecommerce::messages.order_logs.columns.note'))
                ->required()
                ->columnSpanFull(),
            Toggle::make('is_closed')
                ->label(trans('filament-ecommerce::messages.order_logs.columns.is_closed')),
        ]); // TODO: Change the autogenerated stub
    }

    public function table(Table $table): Table
    {
        return $table
            ->headerActions([
                CreateAction::make()->using(function (array $data) {
                    $record = $this->getOwnerRecord();
                    $record->orderLogs()->create([
                        'user_id' => auth()->user()->id,
                        'status' => $record->status,
                        'note' => $data['note'],
                        'is_closed' => $data['is_closed'],
                    ]);

                    return $record;
                }),
            ])
            ->columns([
                TextColumn::make('created_at')
                    ->description(fn ($record) => $record->created_at->diffForHumans())
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('status')
                    ->label(trans('filament-ecommerce::messages.order_logs.columns.status'))
                    ->state(fn ($record) => str($record->status)->ucfirst()->title()->toString())
                    ->description(fn ($record) => $record->note)
                    ->searchable(),
                TextColumn::make('user.name')
                    ->label(trans('filament-ecommerce::messages.order_logs.columns.user_id'))
                    ->numeric()
                    ->sortable(),
                ToggleColumn::make('is_closed')
                    ->label(trans('filament-ecommerce::messages.order_logs.columns.is_closed')),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->defaultSort('created_at', 'desc')
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
