<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use TomatoPHP\FilamentEcommerce\Filament\Resources\CompanyResource\Pages\EditCompany;
use TomatoPHP\FilamentEcommerce\Filament\Resources\CompanyResource\Pages\ListCompanies;
use TomatoPHP\FilamentEcommerce\Filament\Resources\CompanyResource\RelationManagers\CompanyBranches;
use TomatoPHP\FilamentEcommerce\Models\Company;
use TomatoPHP\FilamentLocations\Models\Country;

class CompanyResource extends Resource
{
    protected static ?string $model = Company::class;

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-building-office';

    protected static ?int $navigationSort = 0;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.company.title'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.company.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.company.single'); // TODO: Change the autogenerated stub
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        SpatieMediaLibraryFileUpload::make('logo')
                            ->label(trans('filament-ecommerce::messages.company.columns.logo'))
                            ->collection('logo')
                            ->columnSpanFull()
                            ->image(),
                        TextInput::make('name')
                            ->columnSpanFull()
                            ->label(trans('filament-ecommerce::messages.company.columns.name'))
                            ->required()
                            ->maxLength(255),
                        TextInput::make('email')
                            ->label(trans('filament-ecommerce::messages.company.columns.email'))
                            ->email()
                            ->maxLength(255),
                        TextInput::make('phone')
                            ->label(trans('filament-ecommerce::messages.company.columns.phone'))
                            ->tel()
                            ->maxLength(255),
                        TextInput::make('website')
                            ->url()
                            ->label(trans('filament-ecommerce::messages.company.columns.website'))
                            ->maxLength(255),
                        TextInput::make('ceo')
                            ->label(trans('filament-ecommerce::messages.company.columns.ceo'))
                            ->maxLength(255),
                        TextInput::make('registration_number')
                            ->label(trans('filament-ecommerce::messages.company.columns.registration_number'))
                            ->maxLength(255),
                        TextInput::make('tax_number')
                            ->label(trans('filament-ecommerce::messages.company.columns.tax_number'))
                            ->maxLength(255),
                        Textarea::make('notes')
                            ->label(trans('filament-ecommerce::messages.company.columns.notes'))
                            ->columnSpanFull(),
                    ])->columns(2),
                Section::make()
                    ->schema([
                        Textarea::make('address')
                            ->columnSpanFull()
                            ->label(trans('filament-ecommerce::messages.company.columns.address'))
                            ->maxLength(255),
                        Select::make('country_id')
                            ->searchable()
                            ->options(Country::query()->get()->pluck('name', 'id')->toArray())
                            ->label(trans('filament-ecommerce::messages.company.columns.country_id')),
                        TextInput::make('city')
                            ->label(trans('filament-ecommerce::messages.company.columns.city'))
                            ->maxLength(255),
                        TextInput::make('zip')
                            ->columnSpanFull()
                            ->label(trans('filament-ecommerce::messages.company.columns.zip'))
                            ->maxLength(255),

                    ])->columns(2),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('country.name')
                    ->label(trans('filament-ecommerce::messages.company.columns.country_id'))
                    ->sortable(),
                TextColumn::make('name')
                    ->label(trans('filament-ecommerce::messages.company.columns.name'))
                    ->sortable()
                    ->searchable(),
                TextColumn::make('email')
                    ->label(trans('filament-ecommerce::messages.company.columns.email'))
                    ->sortable()
                    ->searchable(),
                TextColumn::make('phone')
                    ->label(trans('filament-ecommerce::messages.company.columns.phone'))
                    ->sortable()
                    ->searchable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            CompanyBranches::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListCompanies::route('/'),
            'edit' => EditCompany::route('/{record}/edit'),
        ];
    }
}
