<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;
use TomatoPHP\FilamentCms\Models\Category;
use TomatoPHP\FilamentEcommerce\Filament\Resources\CouponResource\Pages\ListCoupons;
use TomatoPHP\FilamentEcommerce\Models\Coupon;
use TomatoPHP\FilamentEcommerce\Models\Product;

class CouponResource extends Resource
{
    protected static ?string $model = Coupon::class;

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-receipt-percent';

    protected static ?int $navigationSort = 5;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.coupons.title'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.coupons.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.coupons.single');
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('code')
                    ->unique(ignoreRecord: true)
                    ->label(trans('filament-ecommerce::messages.coupons.columns.code'))
                    ->default(Str::random(6))
                    ->required()
                    ->maxLength(255),
                Select::make('type')
                    ->searchable()
                    ->label(trans('filament-ecommerce::messages.coupons.columns.type'))
                    ->options([
                        'discount_coupon' => trans('filament-ecommerce::messages.coupons.columns.discount_coupon'),
                        'percentage_coupon' => trans('filament-ecommerce::messages.coupons.columns.percentage_coupon'),
                    ])
                    ->default('discount_coupon'),
                TextInput::make('amount')
                    ->label(trans('filament-ecommerce::messages.coupons.columns.amount'))
                    ->required()
                    ->numeric()
                    ->default(0),
                DatePicker::make('end_at')
                    ->label(trans('filament-ecommerce::messages.coupons.columns.end_at')),
                Toggle::make('is_activated')
                    ->columnSpanFull()
                    ->label(trans('filament-ecommerce::messages.coupons.columns.is_activated')),
                Toggle::make('is_limited')
                    ->columnSpanFull()
                    ->default(false)
                    ->label(trans('filament-ecommerce::messages.coupons.columns.is_limited'))
                    ->live(),
                Repeater::make('apply_to')
                    ->columnSpanFull()
                    ->hidden(fn (Get $get) => ! $get('is_limited'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.apply_to'))
                    ->schema([
                        Select::make('model_type')
                            ->label(trans('filament-ecommerce::messages.coupons.columns.type'))
                            ->searchable()
                            ->options([
                                Product::class => trans('filament-ecommerce::messages.coupons.columns.product'),
                                Category::class => trans('filament-ecommerce::messages.coupons.columns.category'),
                            ])
                            ->live(),
                        Select::make('model_id')
                            ->hidden(fn (Get $get) => $get('model_type') !== Category::class)
                            ->label(trans('filament-ecommerce::messages.coupons.columns.category'))
                            ->searchable()
                            ->options(Category::query()->where('for', 'product')->where('type', 'category')->pluck('name', 'id')->toArray()),
                        Select::make('model_id')
                            ->hidden(fn (Get $get) => $get('model_type') !== Product::class)
                            ->label(trans('filament-ecommerce::messages.coupons.columns.product'))
                            ->searchable()
                            ->options(Product::query()->pluck('name', 'id')->toArray()),
                    ]),
                Repeater::make('except')
                    ->columnSpanFull()
                    ->hidden(fn (Get $get) => ! $get('is_limited'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.except'))
                    ->schema([
                        Select::make('model_type')
                            ->label(trans('filament-ecommerce::messages.coupons.columns.type'))
                            ->searchable()
                            ->options([
                                Product::class => trans('filament-ecommerce::messages.coupons.columns.product'),
                                Category::class => trans('filament-ecommerce::messages.coupons.columns.category'),
                            ])
                            ->live(),
                        Select::make('model_id')
                            ->hidden(fn (Get $get) => $get('model_type') !== Category::class)
                            ->label(trans('filament-ecommerce::messages.coupons.columns.category'))
                            ->searchable()
                            ->options(Category::query()->where('for', 'product')->where('type', 'category')->pluck('name', 'id')->toArray()),
                        Select::make('model_id')
                            ->hidden(fn (Get $get) => $get('model_type') !== Product::class)
                            ->label(trans('filament-ecommerce::messages.coupons.columns.product'))
                            ->searchable()
                            ->options(Product::query()->pluck('name', 'id')->toArray()),
                    ]),
                TextInput::make('use_limit')
                    ->hidden(fn (Get $get) => ! $get('is_limited'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.use_limit'))
                    ->numeric()
                    ->default(0),
                TextInput::make('use_limit_by_user')
                    ->hidden(fn (Get $get) => ! $get('is_limited'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.use_limit_by_user'))
                    ->numeric()
                    ->default(0),
                TextInput::make('order_total_limit')
                    ->hidden(fn (Get $get) => ! $get('is_limited'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.order_total_limit'))
                    ->numeric()
                    ->default(0),

                Toggle::make('is_marketing')
                    ->columnSpanFull()
                    ->live()
                    ->label(trans('filament-ecommerce::messages.coupons.columns.is_marketing')),
                TextInput::make('marketer_name')
                    ->hidden(fn (Get $get) => ! $get('is_marketing'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.marketer_name'))
                    ->maxLength(255),
                TextInput::make('marketer_type')
                    ->hidden(fn (Get $get) => ! $get('is_marketing'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.marketer_type'))
                    ->maxLength(255),
                TextInput::make('marketer_amount')
                    ->hidden(fn (Get $get) => ! $get('is_marketing'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.marketer_amount'))
                    ->numeric(),
                TextInput::make('marketer_amount_max')
                    ->hidden(fn (Get $get) => ! $get('is_marketing'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.marketer_amount_max'))
                    ->numeric(),
                Toggle::make('marketer_show_amount_max')
                    ->hidden(fn (Get $get) => ! $get('is_marketing'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.marketer_show_amount_max')),
                Toggle::make('marketer_hide_total_sales')
                    ->hidden(fn (Get $get) => ! $get('is_marketing'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.marketer_hide_total_sales')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('code')
                    ->copyable()
                    ->icon('heroicon-o-clipboard')
                    ->badge()
                    ->tooltip(trans('filament-ecommerce::messages.coupons.columns.copy'))
                    ->label(trans('filament-ecommerce::messages.coupons.columns.code'))
                    ->searchable(),
                TextColumn::make('type')
                    ->badge()
                    ->icon(fn ($record) => $record->type === 'discount_coupon' ? 'heroicon-o-receipt-refund' : 'heroicon-o-receipt-percent')
                    ->color(fn ($record) => $record->type === 'discount_coupon' ? 'primary' : 'info')
                    ->label(trans('filament-ecommerce::messages.coupons.columns.type'))
                    ->state(fn ($record) => $record->type === 'discount_coupon' ? trans('filament-ecommerce::messages.coupons.columns.discount_coupon') : trans('filament-ecommerce::messages.coupons.columns.percentage_coupon'))
                    ->searchable(),
                TextColumn::make('amount')
                    ->label(trans('filament-ecommerce::messages.coupons.columns.amount'))
                    ->numeric()
                    ->sortable(),
                TextColumn::make('end_at')
                    ->label(trans('filament-ecommerce::messages.coupons.columns.end_at'))
                    ->date()
                    ->sortable(),
                IconColumn::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.coupons.columns.is_activated'))
                    ->boolean(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('type')
                    ->label(trans('filament-ecommerce::messages.coupons.filters.type'))
                    ->searchable()
                    ->options([
                        'discount_coupon' => trans('filament-ecommerce::messages.coupons.columns.discount_coupon'),
                        'percentage_coupon' => trans('filament-ecommerce::messages.coupons.columns.percentage_coupon'),
                    ]),
                TernaryFilter::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.coupons.filters.is_activated')),
                TernaryFilter::make('is_limited')
                    ->label(trans('filament-ecommerce::messages.coupons.filters.is_limited')),
                TernaryFilter::make('is_marketing')
                    ->label(trans('filament-ecommerce::messages.coupons.filters.is_marketing')),
                Filter::make('end_at')
                    ->label(trans('filament-ecommerce::messages.coupons.filters.end_at'))
                    ->schema([
                        DatePicker::make('end_at'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['end_at'],
                                fn (Builder $query, $date): Builder => $query->whereDate('end_at', '>=', $date),
                            );
                    }),
            ])
            ->recordActions([
                EditAction::make(),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [

        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListCoupons::route('/'),
        ];
    }
}
