<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Table;
use Illuminate\Support\Str;
use TomatoPHP\FilamentEcommerce\Filament\Resources\GiftCardResource\Pages\ListGiftCards;
use TomatoPHP\FilamentEcommerce\Models\GiftCard;

class GiftCardResource extends Resource
{
    protected static ?string $model = GiftCard::class;

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-gift';

    protected static ?int $navigationSort = 6;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.gift_card.title'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.gift_card.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.gift_card.single');
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->default(trans('filament-ecommerce::messages.gift_card.columns.default'))
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.name'))
                    ->required()
                    ->maxLength(255),
                TextInput::make('code')
                    ->unique(ignoreRecord: true)
                    ->default(Str::random(6))
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.code'))
                    ->required()
                    ->maxLength(255),
                TextInput::make('balance')
                    ->columnSpanFull()
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.balance'))
                    ->numeric()
                    ->default(0),
                Toggle::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.is_activated')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.name'))
                    ->searchable(),
                TextColumn::make('code')
                    ->copyable()
                    ->icon('heroicon-o-clipboard')
                    ->badge()
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.code'))
                    ->searchable(),
                TextColumn::make('balance')
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.balance'))
                    ->money(locale: 'en', currency: setting('site_currency'))
                    ->sortable(),
                IconColumn::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.is_activated'))
                    ->boolean(),
                IconColumn::make('is_expired')
                    ->label(trans('filament-ecommerce::messages.gift_card.columns.is_expired'))
                    ->boolean(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                TernaryFilter::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.gift_card.filters.is_activated')),
                TernaryFilter::make('is_expired')
                    ->label(trans('filament-ecommerce::messages.gift_card.filters.is_expired')),
            ])
            ->recordActions([
                EditAction::make(),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListGiftCards::route('/'),
        ];
    }
}
