<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\ColorPicker;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\SpatieMediaLibraryImageColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Tables\Enums\FiltersLayout;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Grouping\Group;
use Filament\Tables\Table;
use Illuminate\Support\Str;
use LaraZeus\SpatieTranslatable\Resources\Concerns\Translatable;
use TomatoPHP\FilamentCms\Models\Category;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ProductResource\Pages\CreateProduct;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ProductResource\Pages\EditProduct;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ProductResource\Pages\ListProducts;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ProductResource\RelationManagers\CodesManager;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ProductResource\RelationManagers\ProductReviewManager;
use TomatoPHP\FilamentEcommerce\Models\Product;

class ProductResource extends Resource
{
    use Translatable;

    protected static ?string $model = Product::class;

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-shopping-cart';

    protected static ?int $navigationSort = 2;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.product.title');
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.product.title'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.product.single'); // TODO: Change the autogenerated stub
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('Tabs')
                    ->tabs([
                        Tab::make(trans('filament-ecommerce::messages.product.tabs.details'))
                            ->icon('heroicon-o-information-circle')
                            ->schema([
                                Select::make('type')
                                    ->columnSpanFull()
                                    ->searchable()
                                    ->options([
                                        'product' => trans('filament-ecommerce::messages.product.columns.product'),
                                        'digital' => trans('filament-ecommerce::messages.product.columns.digital'),
                                        'service' => trans('filament-ecommerce::messages.product.columns.service'),
                                    ])
                                    ->label(trans('filament-ecommerce::messages.product.columns.type'))
                                    ->default('product'),
                                TextInput::make('name')
                                    ->label(trans('filament-ecommerce::messages.product.columns.name'))
                                    ->lazy()
                                    ->afterStateUpdated(fn (Get $get, Set $set) => $set('slug', Str::slug($get('name'))))
                                    ->required(),
                                TextInput::make('slug')
                                    ->label(trans('filament-ecommerce::messages.product.columns.slug'))
                                    ->required()
                                    ->maxLength(255),
                                Textarea::make('about')
                                    ->columnSpanFull()
                                    ->label(trans('filament-ecommerce::messages.product.columns.about')),
                                TextInput::make('sku')
                                    ->default(uniqid())
                                    ->label(trans('filament-ecommerce::messages.product.columns.sku'))
                                    ->unique(Product::class, column: 'sku', ignoreRecord: true)
                                    ->maxLength(255),
                                TextInput::make('barcode')
                                    ->label(trans('filament-ecommerce::messages.product.columns.barcode'))
                                    ->unique(Product::class, column: 'barcode', ignoreRecord: true)
                                    ->maxLength(255),
                                TextInput::make('price')
                                    ->label(trans('filament-ecommerce::messages.product.columns.price'))
                                    ->required()
                                    ->numeric()
                                    ->prefix('$'),
                                TextInput::make('vat')
                                    ->label(trans('filament-ecommerce::messages.product.columns.vat'))
                                    ->numeric()
                                    ->prefix('$')
                                    ->default(0),
                                TextInput::make('discount')
                                    ->label(trans('filament-ecommerce::messages.product.columns.discount'))
                                    ->numeric()
                                    ->live()
                                    ->prefix('%')
                                    ->default(0),
                                DateTimePicker::make('discount_to')
                                    ->rule('after:now')
                                    ->hidden(fn (Get $get) => ! $get('discount'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.discount_to')),
                                Toggle::make('is_activated')
                                    ->columnSpanFull()
                                    ->label(trans('filament-ecommerce::messages.product.columns.is_activated')),
                                Toggle::make('is_trend')
                                    ->columnSpanFull()
                                    ->label(trans('filament-ecommerce::messages.product.columns.is_trend')),
                            ])->columns(2),
                        Tab::make(trans('filament-ecommerce::messages.product.tabs.prices'))
                            ->icon('heroicon-o-currency-dollar')
                            ->schema([
                                Toggle::make('is_shipped')
                                    ->label(trans('filament-ecommerce::messages.product.columns.is_shipped')),
                                Toggle::make('has_multi_price')
                                    ->live()
                                    ->label(trans('filament-ecommerce::messages.product.columns.has_multi_price')),
                                Repeater::make('prices')
                                    ->hidden(fn (Get $get) => ! $get('has_multi_price'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.prices'))
                                    ->itemLabel(fn (array $state): ?string => Str::title($state['for']) ?? null)
                                    ->collapsed()
                                    ->collapsible()
                                    ->cloneable()
                                    ->schema([
                                        Select::make('for')
                                            ->searchable()
                                            ->live()
                                            ->options([
                                                'retail' => trans('filament-ecommerce::messages.product.columns.retail'),
                                                'wholesale' => trans('filament-ecommerce::messages.product.columns.wholesale'),
                                                'special' => trans('filament-ecommerce::messages.product.columns.special'),
                                                'items' => trans('filament-ecommerce::messages.product.columns.items'),
                                            ])
                                            ->default('retail')
                                            ->label(trans('filament-ecommerce::messages.product.columns.for'))
                                            ->columnSpanFull()
                                            ->required(),
                                        TextInput::make('qty')
                                            ->hidden(fn (Get $get) => $get('for') !== 'items')
                                            ->label(trans('filament-ecommerce::messages.product.columns.qty'))
                                            ->required()
                                            ->numeric(),
                                        TextInput::make('price')
                                            ->label(trans('filament-ecommerce::messages.product.columns.price'))
                                            ->required()
                                            ->numeric()
                                            ->prefix('$'),
                                        TextInput::make('vat')
                                            ->label(trans('filament-ecommerce::messages.product.columns.vat'))
                                            ->numeric()
                                            ->prefix('$')
                                            ->default(0),
                                        TextInput::make('discount')
                                            ->label(trans('filament-ecommerce::messages.product.columns.discount'))
                                            ->numeric()
                                            ->live()
                                            ->prefix('%')
                                            ->default(0),
                                        DateTimePicker::make('discount_to')
                                            ->rule('after:now')
                                            ->hidden(fn (Get $get) => ! $get('discount'))
                                            ->label(trans('filament-ecommerce::messages.product.columns.discount_to')),
                                    ])->columns(3),
                            ]),
                        Tab::make(trans('filament-ecommerce::messages.product.tabs.stock'))
                            ->icon('heroicon-o-home-modern')
                            ->schema([
                                Toggle::make('is_in_stock')
                                    ->label(trans('filament-ecommerce::messages.product.columns.is_in_stock')),
                                Toggle::make('has_unlimited_stock')
                                    ->label(trans('filament-ecommerce::messages.product.columns.has_unlimited_stock')),
                                Toggle::make('has_max_cart')
                                    ->columnSpanFull()
                                    ->live()
                                    ->label(trans('filament-ecommerce::messages.product.columns.has_max_cart')),
                                TextInput::make('min_cart')
                                    ->hidden(fn (Get $get) => ! $get('has_max_cart'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.min_cart'))
                                    ->numeric(),
                                TextInput::make('max_cart')
                                    ->hidden(fn (Get $get) => ! $get('has_max_cart'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.max_cart'))
                                    ->numeric(),
                                Toggle::make('has_stock_alert')
                                    ->columnSpanFull()
                                    ->live()
                                    ->label(trans('filament-ecommerce::messages.product.columns.has_stock_alert')),
                                TextInput::make('min_stock_alert')
                                    ->hidden(fn (Get $get) => ! $get('has_stock_alert'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.min_stock_alert'))
                                    ->numeric(),
                                TextInput::make('max_stock_alert')
                                    ->hidden(fn (Get $get) => ! $get('has_stock_alert'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.max_stock_alert'))
                                    ->numeric(),
                            ])->columns(2),
                        Tab::make(trans('filament-ecommerce::messages.product.tabs.seo'))
                            ->icon('heroicon-o-magnifying-glass')
                            ->schema([
                                SpatieMediaLibraryFileUpload::make('feature_image')
                                    ->columnSpanFull()
                                    ->collection('feature_image')
                                    ->label(trans('filament-ecommerce::messages.product.columns.feature_image')),
                                SpatieMediaLibraryFileUpload::make('gallery')
                                    ->columnSpanFull()
                                    ->collection('gallery')
                                    ->multiple()
                                    ->reorderable()
                                    ->label(trans('filament-ecommerce::messages.product.columns.gallery')),
                                Select::make('category_id')
                                    ->columnSpanFull()
                                    ->searchable()
                                    ->options(
                                        Category::query()
                                            ->where('for', 'product')
                                            ->where('type', 'category')
                                            ->pluck('name', 'id')
                                            ->toArray()
                                    )
                                    ->label(trans('filament-ecommerce::messages.product.columns.category_id')),
                                Select::make('categories')
                                    ->relationship('categories')
                                    ->multiple()
                                    ->searchable()
                                    ->options(
                                        Category::query()
                                            ->where('for', 'product')
                                            ->where('type', 'category')
                                            ->pluck('name', 'id')
                                            ->toArray()
                                    )
                                    ->label(trans('filament-ecommerce::messages.product.columns.categories')),
                                Select::make('tags')
                                    ->relationship('tags')
                                    ->multiple()
                                    ->searchable()
                                    ->options(
                                        Category::query()
                                            ->where('for', 'product')
                                            ->where('type', 'tag')
                                            ->pluck('name', 'id')
                                            ->toArray()
                                    )
                                    ->label(trans('filament-ecommerce::messages.product.columns.tags')),
                                RichEditor::make('description')
                                    ->columnSpanFull()
                                    ->label(trans('filament-ecommerce::messages.product.columns.description')),
                                RichEditor::make('details')
                                    ->columnSpanFull()
                                    ->label(trans('filament-ecommerce::messages.product.columns.details')),
                                Textarea::make('keywords')
                                    ->columnSpanFull()
                                    ->label(trans('filament-ecommerce::messages.product.columns.keywords')),

                            ])->columns(2),
                        Tab::make(trans('filament-ecommerce::messages.product.tabs.variation'))
                            ->icon('heroicon-o-cursor-arrow-ripple')
                            ->schema([
                                Toggle::make('has_options')
                                    ->live()
                                    ->label(trans('filament-ecommerce::messages.product.columns.has_options')),
                                Repeater::make('options')
                                    ->hidden(fn (Get $get) => ! $get('has_options'))
                                    ->label(trans('filament-ecommerce::messages.product.columns.options.title'))
                                    ->itemLabel(fn (array $state): ?string => $state['name'] ?? null)
                                    ->collapsed()
                                    ->collapsible()
                                    ->cloneable()
                                    ->schema([
                                        TextInput::make('name')
                                            ->label(trans('filament-ecommerce::messages.product.columns.options.name')),
                                        Repeater::make('values')
                                            ->itemLabel(fn (array $state): ?string => $state['value'] ?? null)
                                            ->collapsed()
                                            ->collapsible()
                                            ->cloneable()
                                            ->label(trans('filament-ecommerce::messages.product.columns.options.values'))
                                            ->schema([
                                                TextInput::make('value')
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.value'))
                                                    ->columnSpanFull(),
                                                Toggle::make('has_custom_price')
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.has_custom_price'))
                                                    ->columnSpanFull()
                                                    ->live(),
                                                Select::make('price_for')
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.price_for'))
                                                    ->hidden(fn (Get $get) => ! $get('has_custom_price'))
                                                    ->searchable()
                                                    ->live()
                                                    ->options([
                                                        'retail' => trans('filament-ecommerce::messages.product.columns.retail'),
                                                        'wholesale' => trans('filament-ecommerce::messages.product.columns.wholesale'),
                                                        'special' => trans('filament-ecommerce::messages.product.columns.special'),
                                                        'items' => trans('filament-ecommerce::messages.product.columns.items'),
                                                    ])
                                                    ->default('retail')
                                                    ->required(),
                                                TextInput::make('qty')
                                                    ->hidden(fn (Get $get) => $get('price_for') !== 'items')
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.qty'))
                                                    ->required()
                                                    ->numeric(),
                                                TextInput::make('price')
                                                    ->hidden(fn (Get $get) => ! $get('has_custom_price'))
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.price'))
                                                    ->required()
                                                    ->numeric()
                                                    ->default(0)
                                                    ->prefix('$'),
                                                TextInput::make('vat')
                                                    ->hidden(fn (Get $get) => ! $get('has_custom_price'))
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.vat'))
                                                    ->numeric()
                                                    ->prefix('$')
                                                    ->default(0),
                                                TextInput::make('discount')
                                                    ->hidden(fn (Get $get) => ! $get('has_custom_price'))
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.discount'))
                                                    ->numeric()
                                                    ->live()
                                                    ->prefix('%')
                                                    ->default(0),
                                                DateTimePicker::make('discount_to')
                                                    ->hidden(fn (Get $get) => ! $get('has_custom_price'))
                                                    ->rule('after:now')
                                                    ->hidden(fn (Get $get) => ! $get('discount'))
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.discount_to')),
                                                Toggle::make('has_color')
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.has_color'))
                                                    ->columnSpanFull()
                                                    ->live(),
                                                ColorPicker::make('color')
                                                    ->label(trans('filament-ecommerce::messages.product.columns.options.color'))
                                                    ->hidden(fn (Get $get) => ! $get('has_color')),
                                            ])->columns(4),
                                    ]),
                            ]),
                    ])->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                SpatieMediaLibraryImageColumn::make('feature_image')
                    ->label(trans('filament-ecommerce::messages.product.columns.feature_image'))
                    ->square()
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->collection('feature_image'),
                TextColumn::make('name')
                    ->description(fn (Product $product) => Str::limit($product->about, 50))
                    ->label(trans('filament-ecommerce::messages.product.columns.name'))
                    ->sortable()
                    ->searchable(),
                TextColumn::make('type')
                    ->badge()
                    ->state(fn (Product $product) => match ($product->type) {
                        'product' => trans('filament-ecommerce::messages.product.columns.product'),
                        'digital' => trans('filament-ecommerce::messages.product.columns.digital'),
                        'service' => trans('filament-ecommerce::messages.product.columns.service'),
                    })
                    ->color(fn (Product $product) => match ($product->type) {
                        'product' => 'primary',
                        'digital' => 'success',
                        'service' => 'warning',
                    })
                    ->icon(fn (Product $product) => match ($product->type) {
                        'product' => 'heroicon-s-shopping-cart',
                        'digital' => 'heroicon-s-cloud',
                        'service' => 'heroicon-s-cog',
                    })
                    ->label(trans('filament-ecommerce::messages.product.columns.type'))
                    ->searchable(),
                TextColumn::make('sku')
                    ->label(trans('filament-ecommerce::messages.product.columns.sku'))
                    ->sortable()
                    ->searchable(),
                TextColumn::make('price')
                    ->state(fn (Product $product) => ($product->price + $product->vat) - $product->discount)
                    ->description(fn (Product $product) => '(Price:' . number_format($product->price, 2) . '+VAT:' . number_format($product->vat) . ')-Discount:' . number_format($product->discount))
                    ->label(trans('filament-ecommerce::messages.product.columns.price'))
                    ->money(locale: 'en', currency: setting('site_currency'))
                    ->sortable(),
                ToggleColumn::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.product.columns.is_activated')),
                ToggleColumn::make('is_trend')
                    ->label(trans('filament-ecommerce::messages.product.columns.is_trend')),
                ToggleColumn::make('is_in_stock')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->label(trans('filament-ecommerce::messages.product.columns.is_in_stock')),
                ToggleColumn::make('has_unlimited_stock')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->label(trans('filament-ecommerce::messages.product.columns.has_unlimited_stock')),
                TextColumn::make('category.name')
                    ->badge()
                    ->label(trans('filament-ecommerce::messages.product.columns.category_id'))
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('category_id')
                    ->label(trans('filament-ecommerce::messages.product.filters.category_id'))
                    ->searchable()
                    ->options(
                        Category::query()
                            ->where('for', 'product')
                            ->where('type', 'category')
                            ->pluck('name', 'id')
                            ->toArray()
                    ),
                SelectFilter::make('categories')
                    ->label(trans('filament-ecommerce::messages.product.filters.categories'))
                    ->searchable()
                    ->multiple()
                    ->relationship('categories', 'name')
                    ->options(
                        Category::query()
                            ->where('for', 'product')
                            ->where('type', 'category')
                            ->pluck('name', 'id')
                            ->toArray()
                    ),
                SelectFilter::make('type')
                    ->label(trans('filament-ecommerce::messages.product.filters.type'))
                    ->searchable()
                    ->options([
                        'product' => trans('filament-ecommerce::messages.product.columns.product'),
                        'digital' => trans('filament-ecommerce::messages.product.columns.digital'),
                        'service' => trans('filament-ecommerce::messages.product.columns.service'),
                    ]),
                TernaryFilter::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.product.filters.is_activated')),
                TernaryFilter::make('is_trend')
                    ->label(trans('filament-ecommerce::messages.product.filters.is_trend')),
                TernaryFilter::make('is_shipped')
                    ->label(trans('filament-ecommerce::messages.product.filters.is_shipped')),
                TernaryFilter::make('is_in_stock')
                    ->label(trans('filament-ecommerce::messages.product.filters.is_in_stock')),
                TernaryFilter::make('has_unlimited_stock')
                    ->label(trans('filament-ecommerce::messages.product.filters.has_unlimited_stock')),

            ])
            ->filtersLayout(FiltersLayout::Modal)
            ->groups([
                Group::make('type'),
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            ProductReviewManager::make(),
            CodesManager::make(),
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListProducts::route('/'),
            'create' => CreateProduct::route('/create'),
            'edit' => EditProduct::route('/{record}/edit'),
        ];
    }
}
