<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Illuminate\Support\Str;
use TomatoPHP\FilamentAccounts\Models\Account;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ReferralCodeResource\Pages;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ReferralCodeResource\RelationManagers;
use TomatoPHP\FilamentEcommerce\Models\ReferralCode;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ReferralCodeResource extends Resource
{
    protected static ?string $model = ReferralCode::class;

    protected static ?string $navigationIcon = 'heroicon-o-arrow-top-right-on-square';

    protected static ?int $navigationSort = 7;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.referral_code.title'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.referral_code.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.referral_code.single');
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('account_id')
                    ->columnSpanFull()
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.account_id'))
                    ->searchable()
                    ->options(Account::query()->pluck('name', 'id')->toArray()),
                Forms\Components\TextInput::make('name')
                    ->default(trans('filament-ecommerce::messages.referral_code.columns.default'))
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.name'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('code')
                    ->unique(ignoreRecord: true)
                    ->default(Str::random(6))
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.code'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\Toggle::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_activated')),
                Forms\Components\Toggle::make('is_public')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_public')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('account.name')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.account_id'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('name')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.name'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('code')
                    ->copyable()
                    ->icon('heroicon-o-clipboard')
                    ->badge()
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.code'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('counter')
                    ->badge()
                    ->color('info')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.counter'))
                    ->numeric()
                    ->sortable(),
                Tables\Columns\IconColumn::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_activated'))
                    ->boolean(),
                Tables\Columns\IconColumn::make('is_public')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_public'))
                    ->boolean(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('account_id')
                    ->label(trans('filament-ecommerce::messages.referral_code.filters.account_id'))
                    ->searchable()
                    ->options(Account::query()->pluck('name', 'id')->toArray()),
                Tables\Filters\TernaryFilter::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.referral_code.filters.is_activated')),
                Tables\Filters\TernaryFilter::make('is_public')
                    ->label(trans('filament-ecommerce::messages.referral_code.filters.is_public')),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListReferralCodes::route('/'),
        ];
    }
}
