<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\TernaryFilter;
use Filament\Tables\Table;
use Illuminate\Support\Str;
use TomatoPHP\FilamentAccounts\Models\Account;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ReferralCodeResource\Pages\ListReferralCodes;
use TomatoPHP\FilamentEcommerce\Models\ReferralCode;

class ReferralCodeResource extends Resource
{
    protected static ?string $model = ReferralCode::class;

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-arrow-top-right-on-square';

    protected static ?int $navigationSort = 7;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.referral_code.title'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.referral_code.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.referral_code.single');
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('account_id')
                    ->columnSpanFull()
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.account_id'))
                    ->searchable()
                    ->options(Account::query()->pluck('name', 'id')->toArray()),
                TextInput::make('name')
                    ->default(trans('filament-ecommerce::messages.referral_code.columns.default'))
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.name'))
                    ->required()
                    ->maxLength(255),
                TextInput::make('code')
                    ->unique(ignoreRecord: true)
                    ->default(Str::random(6))
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.code'))
                    ->required()
                    ->maxLength(255),
                Toggle::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_activated')),
                Toggle::make('is_public')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_public')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('account.name')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.account_id'))
                    ->sortable(),
                TextColumn::make('name')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.name'))
                    ->searchable(),
                TextColumn::make('code')
                    ->copyable()
                    ->icon('heroicon-o-clipboard')
                    ->badge()
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.code'))
                    ->searchable(),
                TextColumn::make('counter')
                    ->badge()
                    ->color('info')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.counter'))
                    ->numeric()
                    ->sortable(),
                IconColumn::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_activated'))
                    ->boolean(),
                IconColumn::make('is_public')
                    ->label(trans('filament-ecommerce::messages.referral_code.columns.is_public'))
                    ->boolean(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('account_id')
                    ->label(trans('filament-ecommerce::messages.referral_code.filters.account_id'))
                    ->searchable()
                    ->options(Account::query()->pluck('name', 'id')->toArray()),
                TernaryFilter::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.referral_code.filters.is_activated')),
                TernaryFilter::make('is_public')
                    ->label(trans('filament-ecommerce::messages.referral_code.filters.is_public')),
            ])
            ->recordActions([
                EditAction::make(),
                DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListReferralCodes::route('/'),
        ];
    }
}
