<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Tables\Table;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ShippingVendorResource\Pages\EditShippingVendor;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ShippingVendorResource\Pages\ListShippingVendors;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ShippingVendorResource\RelationManagers\ShippingDeliveryBoys;
use TomatoPHP\FilamentEcommerce\Filament\Resources\ShippingVendorResource\RelationManagers\ShippingVendorPrices;
use TomatoPHP\FilamentEcommerce\Models\ShippingVendor;

class ShippingVendorResource extends Resource
{
    protected static ?string $model = ShippingVendor::class;

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-truck';

    protected static ?int $navigationSort = 1;

    public static function getNavigationGroup(): ?string
    {
        return trans('filament-ecommerce::messages.group'); // TODO: Change the autogenerated stub
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-ecommerce::messages.shipping.title');
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-ecommerce::messages.shipping.title'); // TODO: Change the autogenerated stub
    }

    public static function getLabel(): ?string
    {
        return trans('filament-ecommerce::messages.shipping.single'); // TODO: Change the autogenerated stub
    }

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                SpatieMediaLibraryFileUpload::make('logo')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.logo'))
                    ->columnSpanFull()
                    ->collection('logo')
                    ->image(),
                TextInput::make('name')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.name'))
                    ->required()
                    ->maxLength(255),
                TextInput::make('phone')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.phone'))
                    ->tel()
                    ->maxLength(255),
                Textarea::make('address')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.address'))
                    ->columnSpanFull()
                    ->maxLength(255),
                TextInput::make('contact_person')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.contact_person'))
                    ->maxLength(255),
                TextInput::make('delivery_estimation')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.delivery_estimation'))
                    ->maxLength(255),
                TextInput::make('price')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.price'))
                    ->numeric()
                    ->columnSpanFull()
                    ->required()
                    ->default(0)
                    ->prefix('$'),
                Toggle::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.is_activated')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.name'))
                    ->searchable(),
                TextColumn::make('contact_person')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.contact_person'))
                    ->searchable(),
                TextColumn::make('delivery_estimation')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.delivery_estimation'))
                    ->searchable(),
                TextColumn::make('phone')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.phone'))
                    ->searchable(),
                TextColumn::make('address')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.address'))
                    ->searchable(),
                ToggleColumn::make('is_activated')
                    ->label(trans('filament-ecommerce::messages.shipping.columns.is_activated')),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            ShippingDeliveryBoys::make(),
            ShippingVendorPrices::make(),
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListShippingVendors::route('/'),
            'edit' => EditShippingVendor::route('/{record}/edit'),
        ];
    }
}
