<?php

namespace TomatoPHP\FilamentEcommerce\Filament\Resources\OrderResource\Pages;

use TomatoPHP\FilamentEcommerce\Filament\Pages\OrderSettingsPage;
use TomatoPHP\FilamentEcommerce\Filament\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use TomatoPHP\FilamentTypes\Models\Type;

class ListOrders extends ListRecords
{
    protected static string $resource = OrderResource::class;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        $types = collect([
            [
                'for' => "orders",
                "type" => "source",
                'name' => [
                    'en' => 'System',
                    'ar' => 'النظام',
                ],
                'key' => 'system',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "source",
                'name' => [
                    'en' => 'Website',
                    'ar' => 'الموقع الالكتروني',
                ],
                'key' => 'web',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "source",
                'name' => [
                    'en' => 'Mobile App',
                    'ar' => 'تطبيق الهاتف',
                ],
                'key' => 'app',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "source",
                'name' => [
                    'en' => 'Callcenter',
                    'ar' => 'خدمة العملاء',
                ],
                'key' => 'phone',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "source",
                'name' => [
                    'en' => 'POS',
                    'ar' => 'نقاط البيع',
                ],
                'key' => 'pos',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "source",
                'name' => [
                    'en' => 'Other',
                    'ar' => 'إخري',
                ],
                'key' => 'other',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "payment_methods",
                'name' => [
                    'en' => 'Cash',
                    'ar' => 'كاش',
                ],
                'key' => 'cash',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "payment_methods",
                'name' => [
                    'en' => 'Credit',
                    'ar' => 'بوابة دفع',
                ],
                'key' => 'credit',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "payment_methods",
                'name' => [
                    'en' => 'Wallet',
                    'ar' => 'المحفظة',
                ],
                'key' => 'wallet',
                'icon' => 'heroicon-o-clock',
                'color' => 'danger'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Pending',
                    'ar' => 'تحت المراجعة',
                ],
                'key' => 'pending',
                'icon' => 'heroicon-s-clock',
                'color' => '#d92121'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Preparing',
                    'ar' => 'جاري تحضيره',
                ],
                'key' => 'prepared',
                'icon' => 'heroicon-c-arrow-path-rounded-square',
                'color' => '#ffb000'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Withdrew From Warehouse',
                    'ar' => 'تم صرفة من المخزن',
                ],
                'key' => 'withdrew',
                'icon' => 'heroicon-s-arrow-right-circle',
                'color' => '#7e13de'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Shipped',
                    'ar' => 'تم شحنه',
                ],
                'key' => 'shipped',
                'icon' => 'heroicon-s-truck',
                'color' => '#18bae6'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Delivered',
                    'ar' => 'تم التوصيل',
                ],
                'key' => 'delivered',
                'icon' => 'heroicon-c-check-circle',
                'color' => '#24cc15'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Part Delivered',
                    'ar' => 'تم التوصيل جزئياً',
                ],
                'key' => 'part-delivered',
                'icon' => 'heroicon-c-arrow-uturn-up',
                'color' => '#db0096'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Cancelled',
                    'ar' => 'تم الإلغاء',
                ],
                'key' => 'cancelled',
                'icon' => 'heroicon-c-exclamation-triangle',
                'color' => '#e01212'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Refunded',
                    'ar' => 'تم الاسترجاع',
                ],
                'key' => 'refunded',
                'icon' => 'heroicon-c-archive-box-x-mark',
                'color' => '#e0d213'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Done Order',
                    'ar' => 'طلب نجاح',
                ],
                'key' => 'done',
                'icon' => 'heroicon-m-shield-check',
                'color' => '#21c227'
            ],
            [
                'for' => "orders",
                "type" => "status",
                'name' => [
                    'en' => 'Paid',
                    'ar' => 'مدفوع',
                ],
                'key' => 'paid',
                'icon' => 'heroicon-c-arrow-down-tray',
                'color' => '#7d6df5'
            ],
        ])->each(fn($type) => Type::query()->firstOrCreate([
            'key' => $type['key'],
            'for' => $type['for'],
            'type' => $type['type'],
        ],$type));

    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\Action::make('setting')
                ->hidden(!filament('filament-ecommerce')->useOrderSettings)
                ->hiddenLabel()
                ->tooltip(trans('filament-ecommerce::messages.orders.actions.settings'))
                ->color('warning')
                ->url(OrderSettingsPage::getUrl())
                ->icon('heroicon-o-cog'),
            Actions\CreateAction::make()
            ->hidden(!filament('filament-ecommerce')->allowOrderCreate),
        ];
    }
}
